ALTER TABLE TK_TASK_LIST ENGINE=InnoDB;
ALTER TABLE TK_TASK_LIST_comments ENGINE=InnoDB;
ALTER TABLE TK_TASK_LIST_files ENGINE=InnoDB;
ALTER TABLE TK_TASK_LIST_links ENGINE=InnoDB;
ALTER TABLE TK_TASK_LIST_tags ENGINE=InnoDB;
ALTER TABLE TK_TASK_LIST_tasks ENGINE=InnoDB;