ALTER TABLE SA_CONTACTS ENGINE=InnoDB;
ALTER TABLE SA_CONTACTS_Assistants ENGINE=InnoDB;
ALTER TABLE SA_CONTACTS_Communications ENGINE=InnoDB;
ALTER TABLE SA_CONTACTS_RelatedContacts ENGINE=InnoDB;
ALTER TABLE SA_CONTACTS_ReportsTo ENGINE=InnoDB;
ALTER TABLE SA_CONTACTS_Tags ENGINE=InnoDB;