
APP = 'site'
XIMPIA = 'ximpia'
TWITTER = 'twitter'
FACEBOOK = 'facebook'
XING = 'xing'
LINKEDIN = 'linkedin'
GOOGLE = 'google'
EMAIL = 'email'
PASSWORD = 'password'
SMS = 'sms'
FILE_QUOTA_DEFAULT = 2000
FILE_QUOTA_ORG = 5000
MSG_MODE_REC = 'received'
MSG_MODE_SENT = 'sent'
USER_SETTINGS = 'user_settings'
SETTINGS_ALLOW_PRIVATE_GRP_SUBS = 'ALLOW_PRIVATE_GRP_SUBS'
NUMBER_MATCHES = 10
OK = 'ok'
BLOCKED = 'blocked'
UNBLOCKED = 'unblocked'
ERROR = 'error'
ARCHIVE = 'archive'
UNARCHIVE = 'unarchive'
PROFESSIONAL = 'professional'
USER = 'user'
ORGANIZATION = 'organization'
SETTINGS_DEFAULT = ''
IMPORT = 'import'
GMAIL = 'gmail'
YAHOO = 'yahoo'
MSN = 'msn'
HOME = 'home'
WORK = 'work'
MOBILE = 'mobile'
WORK_MOBILE = 'work_mobile'
FAX = 'fax'
NETWORK = 'network'
SITE = 'site'
BLOG = 'blog'
FACEBOOK_PAGE = 'facebook_page'
IM = 'im'
RESERVED_GROUP_NAME_LIST = ['ximpia']
PENDING = 'pending'
USED = 'used'
NUMBER_INVITATIONS_USER = 15
NUMBER_INVITATIONS_STAFF = 500
SOCIAL_NETWORK = 'social_network'

# Signup constants
SIGNUP_USER_GROUP_ID = '1'

# Parameters
PARAM_LOGIN = 'LOGIN'
PARAM_REMINDER_DAYS = 'REMINDER_DAYS'
