ALTER TABLE HR_CURRICULUM ENGINE=InnoDB;
ALTER TABLE HR_CURRICULUM_Education ENGINE=InnoDB;
ALTER TABLE HR_CURRICULUM_EducationOnline ENGINE=InnoDB;
ALTER TABLE HR_CURRICULUM_WorkExperience ENGINE=InnoDB;