ALTER TABLE HR_FILES ENGINE=InnoDB;
ALTER TABLE HR_FILES_Shares ENGINE=InnoDB;
ALTER TABLE HR_FILES_Comments ENGINE=InnoDB;
ALTER TABLE HR_FILES_Likes ENGINE=InnoDB;
ALTER TABLE HR_FILES_Tags ENGINE=InnoDB;