ALTER TABLE HR_PARAMS ENGINE=InnoDB;
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('relationship','single','Single',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('relationship','relationship','In a Relationship',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('relationship','engaged','Engaged',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('relationship','married','Married',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('relationship','complicated','It\'s Complicated',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('relationship','open','In An Open Relationship',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('relationship','widowed','Widowed',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('mode','site','Site',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('mode','email','Email',1,NOW(),0);
INSERT INTO HR_PARAMS (`Mode`,`Name`,`Value`,`UserCreateId`,`DateCreate`,`Delete`) VALUES ('mode','im','Instant Messenger',1,NOW(),0);