ALTER TABLE HR_ORGANIZATION ENGINE=InnoDB;
ALTER TABLE HR_ORGANIZATION_Groups ENGINE=InnoDB;
ALTER TABLE HR_ORGANIZATION_SocialNetworks ENGINE=InnoDB;
ALTER TABLE HR_ORGANIZATION_Taxes ENGINE=InnoDB;
ALTER TABLE HR_ORGANIZATION_Addresses ENGINE=InnoDB;
ALTER TABLE HR_ORGANIZATION_RelatedToDown ENGINE=InnoDB;
ALTER TABLE HR_ORGANIZATION_RelatedToUp ENGINE=InnoDB;
ALTER TABLE HR_ORGANIZATION_Industries ENGINE=InnoDB;