ALTER TABLE HR_USER_PROFILES ENGINE=InnoDB;
ALTER TABLE HR_USER_PROFILES_Site ENGINE=InnoDB;
ALTER TABLE HR_USER_PROFILES_IM ENGINE=InnoDB;
ALTER TABLE HR_USER_PROFILES_Email ENGINE=InnoDB;
ALTER TABLE HR_USER_PROFILES_Likes ENGINE=InnoDB;
ALTER TABLE HR_USER_PROFILES_Shares ENGINE=InnoDB;
ALTER TABLE HR_USER_PROFILES_Comments ENGINE=InnoDB;