ALTER TABLE HR_PROFESSIONAL ENGINE=InnoDB;
ALTER TABLE HR_PROFESSIONAL_Taxes ENGINE=InnoDB;
ALTER TABLE HR_PROFESSIONAL_Skills ENGINE=InnoDB;
ALTER TABLE HR_PROFESSIONAL_RelatedToUp ENGINE=InnoDB;
ALTER TABLE HR_PROFESSIONAL_RelatedToDown ENGINE=InnoDB;
ALTER TABLE HR_PROFESSIONAL_ProfessionalRelations ENGINE=InnoDB;
ALTER TABLE HR_PROFESSIONAL_Identifiers ENGINE=InnoDB;
ALTER TABLE HR_PROFESSIONAL_Industries ENGINE=InnoDB;