
# Constants
USER = 'user'
XIMPIA = 'ximpia'
TWITTER = 'twitter'
FACEBOOK = 'facebook'
LINKEDIN = 'linkedin'
GOOGLE = 'google'
EMAIL = 'email'
SMS = 'sms'
READ = 'read'
UPDATE = 'update'
DELETE = 'delete'
WF = 'wf'
ZONE = 'zone'
GROUP = 'group'
MENU_NAME = 'menuName'
VIEW = 'view'
SEP = 'sep'

# Params
PARAM_COMMTYPE = 'COMMTYPE'
PARAM_ICON = 'ICON'
PARAM_CHANNEL = 'CHANNEL'
PARAM_META_TYPE = 'META_TYPE'
