ALTER TABLE US_STATUS_STREAM ENGINE=InnoDB;
ALTER TABLE US_STATUS_STREAM_Comment ENGINE=InnoDB;
ALTER TABLE US_STATUS_STREAM_Like ENGINE=InnoDB;
ALTER TABLE US_STATUS_STREAM_Share ENGINE=InnoDB;
ALTER TABLE US_STATUS_STREAM_Tags ENGINE=InnoDB;